#+TITLE: git-migrate
#+AUTHOR: Matthew Kennedy
#+DATE: <2025-12-22 Mon>
#+PROPERTY: header-args:go :noweb yes

* Introduction

git-migrate is a command-line tool created with the intent of making the move
from one git forge to another more convenient.

Supported forges include:
- Github
- Codeberg
- Forgejo

Forges to add include:
- Sourcehut
- Gitlab main
- Gitlab self-host
- Gitea

* Package and Imports

Every Go program starts with a package declaration and imports:

#+NAME: package-and-imports
#+BEGIN_SRC go
package main

import (
	"fmt"
	"log"
	
	"github.com/charmbracelet/huh"
	"github.com/joho/godotenv"
)
#+END_SRC

* 

** Forge request structure

This defines what attributes are to be queried by the program in regards to
forge information (Github, Codeberg, Forgejo, etc.)

#+NAME: forge-struct
#+BEGIN_SRC go
func placholder() {
	fmt.Println("Hello, World!")
}
#+END_SRC

#+NAME: repo-struct
#+BEGIN_SRC go
func placholder() {
	fmt.Println("Goodbye, Mars!")
}
#+END_SRC

* Github
This is placeholder text.

* Codeberg
This is placeholder text.

* Forgejo
This is placeholder text.

# * Gitea

# * Gitlab

# * Gitlab (self-hosted)

# * Sourcehut

* Main Function

** Complete Program

This is the final tangled output combining all sections:

#+BEGIN_SRC go :tangle main.go
<<package-and-imports>>

<<forge-struct>>

<<repo-struct>>

<<main-function>>
#+END_SRC

* Usage


